package kr.or.visitkorea.admin.client.manager;

public interface ApplicationListAll {
    public static final String WINDOW_KEY_MOBILE_MAIN = "WINDOW_KEY_MOBILE_MAIN";
    public static final String WINDOW_KEY_PC_MAIN = "WINDOW_KEY_PC_MAIN";
    public static final String WINDOW_KEY_ACCOUNT = "WINDOW_KEY_ACCOUNT";
    public static final String WINDOW_KEY_TAGS = "WINDOW_KEY_TAGS";
    public static final String WINDOW_KEY_RECOMM_MAIN = "WINDOW_KEY_RECOMM_MAIN";
    public static final String WINDOW_KEY_COURSE_MAIN = "WINDOW_KEY_COURSE_MAIN";
    public static final String WINDOW_KEY_SIGHTS_MAIN = "WINDOW_KEY_SIGHTS_MAIN";
    public static final String WINDOW_KEY_FESTIVAL_MAIN = "WINDOW_KEY_FESTIVAL_MAIN";
    public static final String WINDOW_KEY_EVENT_MAIN = "WINDOW_KEY_EVENT_MAIN";
    public static final String WINDOW_KEY_RECOMM_CONTENT = "WINDOW_KEY_RECOMM_CONTENT";
	public static final String WINDOW_KEY_COURSE_CONTENT = "WINDOW_KEY_COURSE_CONTENT";
	public static final String WINDOW_KEY_DATABASE_CONTENT = "WINDOW_KEY_DATABASE_CONTENT";
	public static final String WINDOW_KEY_FOOD_API_MANAGER = "WINDOW_KEY_FOOD_API_MANAGER";
	public static final String WINDOW_KEY_LOGIN = "WINDOW_KEY_LOGIN";
	public static final String WINDOW_KEY_OTHER_DEPARTMENT_MAIN_CONTENT = "WINDOW_KEY_OTHER_DEPARTMENT_MAIN_CONTENT";
	public static final String WINDOW_KEY_CONTENT_PREVIEW = "WINDOW_KEY_CONTENT_PREVIEW";
	public static final String WINDOW_MAIN_SHOWCASE = "WINDOW_MAIN_SHOWCASE";
	public static final String WINDOW_MAIN_CURATION = "WINDOW_MAIN_CURATION";
	public static final String WINDOW_MAIN_MARKETING = "WINDOW_MAIN_MARKETING";
	public static final String WINDOW_MAIN_CALENDAR = "WINDOW_MAIN_CALENDAR";
	public static final String WINDOW_MAIN_DEPARTMENT = "WINDOW_MAIN_DEPARTMENT";
	public static final String WINDOW_MAIN_LOCAL_GOVERNMENT = "WINDOW_MAIN_LOCAL_GOVERNMENT";
	public static final String WINDOW_KEY_MAIN_CONTENT = "WINDOW_KEY_MAIN_CONTENT";
	public static final String WINDOW_KEY_MAIN_CONTENT_MOBILE = "WINDOW_KEY_MAIN_CONTENT_MOBILE";
	public static final String WINDOW_KEY_MAIN_CONTENT_RECOMM = "WINDOW_KEY_MAIN_CONTENT_RECOMM";
	public static final String WINDOW_KEY_MAIN_CONTENT_CORUSE = "WINDOW_KEY_MAIN_CONTENT_CORUSE";
	public static final String WINDOW_KEY_MAIN_CONTENT_SIGESE = "WINDOW_KEY_MAIN_CONTENT_SIGESE";
	public static final String WINDOW_KEY_MAIN_CONTENT_FESTIV = "WINDOW_KEY_MAIN_CONTENT_FESTIV";
	public static final String WINDOW_KEY_NEWS = "WINDOW_KEY_NEWS";
	        
	// 최진석 2018.09.28
	public static final String WINDOW_MEMBER = "WINDOW_MEMBER";
	public static final String WINDOW_MEMBER_ACTIVITY = "WINDOW_MEMBER_ACTIVITY";
	public static final String WINDOW_MEMBER_ACTIVITY_COMMENT = "WINDOW_MEMBER_ACTIVITY_COMMENT";
	public static final String WINDOW_MEMBER_ACTIVITY_COURSE = "WINDOW_MEMBER_ACTIVITY_COURSE";
	public static final String WINDOW_MEMBER_ACTIVITY_QNA = "WINDOW_MEMBER_ACTIVITY_QNA";
	public static final String WINDOW_MEMBER_ACTIVITY_ZIKIMI = "WINDOW_MEMBER_ACTIVITY_ZIKIMI";
	
	public static final String WINDOW_ADBANNER_MANAGER = "WINDOW_ADBANNER_MANAGER";
	
	public static final String WINDOW_DEPARTMENT_MANAGER = "WINDOW_DEPARTMENT_MANAGER";

	public static final String WINDOW_KEY_TOUR_GUIDE_BOOK = "WINDOW_KEY_TOUR_GUIDE_BOOK";
	public static final String WINDOW_KEY_IMAGE_UPLOAD = "WINDOW_KEY_IMAGE_UPLOAD";
	public static final String WINDOW_KEY_IMAGE_MANAGER = "WINDOW_KEY_IMAGE_MANAGER";
	public static final String WINDOW_KEY_TOUR_API = "WINDOW_KEY_TOUR_API";

	public static final String WINDOW_KEY_APP_VERSION = "WINDOW_KEY_APP_VERSION";
	public static final String WINDOW_KEY_FCM_PUSH = "WINDOW_KEY_FCM_PUSH";
	
	public static final String WINDOW_ANALYSIS_MAIN = "WINDOW_ANALYSIS_MAIN";
	public static final String WINDOW_ANALYSIS_TAG= "WINDOW_ANALYSIS_TAG";
	public static final String WINDOW_ANALYSIS_AREA= "WINDOW_ANALYSIS_AREA";
	public static final String WINDOW_ANALYSIS_CONTENTS = "WINDOW_ANALYSIS_CONTENTS";
	public static final String WINDOW_ANALYSIS_BANNER = "WINDOW_ANALYSIS_BANNER";
	public static final String WINDOW_ANALYSIS_CONNECT = "WINDOW_ANALYSIS_CONNECT";
	public static final String WINDOW_ANALYSIS_OTHERDEP = "WINDOW_ANALYSIS_OTHERDEP";
	
	public static final String WINDOW_PARTNERS_CONTENT = "WINDOW_PARTNERS_CONTENT";
	public static final String WINDOW_PARTNERS_CHANNEL = "WINDOW_PARTNERS_CHANNEL";
	public static final String WINDOW_PARTNERS_ACTIVITY = "WINDOW_PARTNERS_ACTIVITY";
	public static final String WINDOW_PARTNERS_AFFILIATE_PROPOSAL = "WINDOW_PARTNERS_AFFILIATE_PROPOSAL";
	
	public static final String WINDOW_REPAIR = "WINDOW_REPAIR";
	
	public static final String WINDOW_KEY_SERVICE_MANAGEMENT = "WINDOW_KEY_SERVICE_MANAGEMENT";
	
	public static final String WINDOW_KEY_SUB_TAG = "WINDOW_KEY_SUB_TAG";
	public static final String WINDOW_KEY_EVENT_MANAGER = "WINDOW_KEY_EVENT_MANAGER";
	public static final String WINDOW_KEY_EVENT_BLACKLIST = "WINDOW_KEY_EVENT_BLACKLIST";
	public static final String WINDOW_KEY_EVENT_DASHBOARD = "WINDOW_KEY_EVENT_DASHBOARD";
	public static final String WINDOW_KEY_EVENT_DASHBOARD_USER = "WINDOW_KEY_EVENT_DASHBOARD_USER";
	public static final String WINDOW_KEY_EVENT_DASHBOARD_ACCESS = "WINDOW_KEY_EVENT_DASHBOARD_ACCESS";
	public static final String WINDOW_KEY_AUTHOR_MANAGER = "WINDOW_KEY_AUTHOR_MANAGER";
	
	public static final String WINDOW_ADD_MENU = "WINDOW_ADD_MENU";
	public static final String WINDOW_CODE_MANAGER = "WINDOW_CODE_MANAGER";
	public static final String WINDOW_KILLER_CONTENT_MANAGER = "WINDOW_KILLER_CONTENT_MANAGER";
	public static final String WINDOW_SERVER_MONITORING = "WINDOW_SERVER_MONITORING";
	public static final String WINDOW_KEY_ADVERTISEMENT = "WINDOW_KEY_ADVERTISEMENT";
	public static final String WINDOW_STAMP_EVENT_STATS = "WINDOW_STAMP_EVENT_STATS";
}
