package kr.or.visitkorea.admin.client.manager.contents.database;

public enum DatabaseContentType {
	
	PREVIEW, 
	INPUT_HTML, 
	INPUT_TEXT, 
	INPUT_SELECT, 
	NONE, 
	INPUT_IMAGE, 
	INPUT_IMAGES, 
	INPUT_MOVIE, 
	INPUT_ADDITIONAL_INFORMATION, 
	INPUT_COURSE_DETAIL,
	INPUT_CITY_TOUR_DETAIL,
	INPUT_ACCOMMODATION_DETAIL, 
	INPUT_BOOLEAN, 
	INPUT_CLOSING_LINE,
	INPUT_TRAVEL_INFO,
	INPUT_COUPON_INFO
}
